Get-ADComputer -Filter * -Properties Created,LastLogonDate,modifyTimeStamp,OperatingSystem,whencreated,whenchanged | 
Select-Object -Property Name,OperatingSystem,Enabled,whencreated,Created,whenchanged,modifyTimeStamp,LastLogonDate,DistinguishedName
<#
Ref: All the properties of get-adcomputer output:
PS C:\WINDOWS\system32> Get-ADComputer -Filter * -Properties * | gm


   TypeName: Microsoft.ActiveDirectory.Management.ADComputer

Name                                 MemberType            Definition          
----                                 ----------            ----------          
Contains                             Method                bool Contains(str...
Equals                               Method                bool Equals(Syste...
GetEnumerator                        Method                System.Collection...
GetHashCode                          Method                int GetHashCode()   
GetType                              Method                type GetType()      
ToString                             Method                string ToString()   
Item                                 ParameterizedProperty Microsoft.ActiveD...
AccountExpirationDate                Property              System.DateTime A...
accountExpires                       Property              System.Int64 acco...
AccountLockoutTime                   Property              System.DateTime A...
AccountNotDelegated                  Property              System.Boolean Ac...
AllowReversiblePasswordEncryption    Property              System.Boolean Al...
AuthenticationPolicy                 Property              Microsoft.ActiveD...
AuthenticationPolicySilo             Property              Microsoft.ActiveD...
BadLogonCount                        Property              System.Int32 BadL...
badPasswordTime                      Property              System.Int64 badP...
badPwdCount                          Property              System.Int32 badP...
CannotChangePassword                 Property              System.Boolean Ca...
CanonicalName                        Property              System.String Can...
Certificates                         Property              Microsoft.ActiveD...
CN                                   Property              System.String CN ...
codePage                             Property              System.Int32 code...
CompoundIdentitySupported            Property              Microsoft.ActiveD...
countryCode                          Property              System.Int32 coun...
Created                              Property              System.DateTime C...
createTimeStamp                      Property              System.DateTime c...
Deleted                              Property              System.Boolean De...
Description                          Property              System.String Des...
DisplayName                          Property              System.String Dis...
DistinguishedName                    Property              System.String Dis...
DNSHostName                          Property              System.String DNS...
DoesNotRequirePreAuth                Property              System.Boolean Do...
dSCorePropagationData                Property              Microsoft.ActiveD...
Enabled                              Property              System.Boolean En...
HomedirRequired                      Property              System.Boolean Ho...
HomePage                             Property              System.String Hom...
instanceType                         Property              System.Int32 inst...
IPv4Address                          Property              System.String IPv...
IPv6Address                          Property              System.String IPv...
isCriticalSystemObject               Property              System.Boolean is...
isDeleted                            Property              System.Boolean is...
KerberosEncryptionType               Property              Microsoft.ActiveD...
LastBadPasswordAttempt               Property              System.DateTime L...
LastKnownParent                      Property              System.String Las...
lastLogoff                           Property              System.Int64 last...
lastLogon                            Property              System.Int64 last...
LastLogonDate                        Property              System.DateTime L...
lastLogonTimestamp                   Property              System.Int64 last...
localPolicyFlags                     Property              System.Int32 loca...
Location                             Property              System.String Loc...
LockedOut                            Property              System.Boolean Lo...
logonCount                           Property              System.Int32 logo...
ManagedBy                            Property              System.String Man...
MemberOf                             Property              Microsoft.ActiveD...
MNSLogonAccount                      Property              System.Boolean MN...
Modified                             Property              System.DateTime M...
modifyTimeStamp                      Property              System.DateTime m...
msDFSR-ComputerReferenceBL           Property              Microsoft.ActiveD...
msDS-GenerationId                    Property              System.Byte[] msD...
msDS-SupportedEncryptionTypes        Property              System.Int32 msDS...
msDS-User-Account-Control-Computed   Property              System.Int32 msDS...
Name                                 Property              System.String Nam...
nTSecurityDescriptor                 Property              System.DirectoryS...
ObjectCategory                       Property              System.String Obj...
ObjectClass                          Property              System.String Obj...
ObjectGUID                           Property              System.Nullable`1...
objectSid                            Property              System.Security.P...
OperatingSystem                      Property              System.String Ope...
OperatingSystemHotfix                Property              System.String Ope...
OperatingSystemServicePack           Property              System.String Ope...
OperatingSystemVersion               Property              System.String Ope...
PasswordExpired                      Property              System.Boolean Pa...
PasswordLastSet                      Property              System.DateTime P...
PasswordNeverExpires                 Property              System.Boolean Pa...
PasswordNotRequired                  Property              System.Boolean Pa...
PrimaryGroup                         Property              System.String Pri...
primaryGroupID                       Property              System.Int32 prim...
PrincipalsAllowedToDelegateToAccount Property              Microsoft.ActiveD...
ProtectedFromAccidentalDeletion      Property              System.Boolean Pr...
pwdLastSet                           Property              System.Int64 pwdL...
rIDSetReferences                     Property              Microsoft.ActiveD...
SamAccountName                       Property              System.String Sam...
sAMAccountType                       Property              System.Int32 sAMA...
sDRightsEffective                    Property              System.Int32 sDRi...
serverReferenceBL                    Property              Microsoft.ActiveD...
ServiceAccount                       Property              Microsoft.ActiveD...
servicePrincipalName                 Property              Microsoft.ActiveD...
ServicePrincipalNames                Property              Microsoft.ActiveD...
SID                                  Property              System.Security.P...
SIDHistory                           Property              Microsoft.ActiveD...
TrustedForDelegation                 Property              System.Boolean Tr...
TrustedToAuthForDelegation           Property              System.Boolean Tr...
UseDESKeyOnly                        Property              System.Boolean Us...
userAccountControl                   Property              System.Int32 user...
userCertificate                      Property              Microsoft.ActiveD...
UserPrincipalName                    Property              System.String Use...
uSNChanged                           Property              System.Int64 uSNC...
uSNCreated                           Property              System.Int64 uSNC...
whenChanged                          Property              System.DateTime w...
whenCreated                          Property              System.DateTime w...
#>
